version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_ml
    ports:
      - "8000:80"  # Changé de 80:80 à 8000:80
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./src/pages:/shared/data

  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "8080:80"  # Port 8080 reste le même
    depends_on:
      - fastapi
    restart: unless-stopped
    volumes:
      - ./src/pages:/shared/data