FROM nginx:alpine

COPY ./src/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./src/css /usr/share/nginx/html/css
COPY ./src/pages /usr/share/nginx/html/pages

RUN echo '<html><head><title>CommVulnHunter</title></head><body><h1>CommVulnHunter</h1><p><a href="/pages/">Pages</a></p></body></html>' > /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]