version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_ml
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1

  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "8080:80"
