version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_ml
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "8080:80"
    depends_on:
      - fastapi
    restart: unless-stopped